QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	[`weapon_ak47`] 		 	= {['name'] = 'weapon_ak47', 	 	['label'] = 'AK-47', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_m70`] 			    = {['name'] = 'weapon_m70', 	 	['label'] = 'M70', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_de`] 			 	= {['name'] = 'weapon_de', 		['label'] = 'Desert Eagle', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_fnx45`] 			= {['name'] = 'weapon_fnx45', 		['label'] = 'FN FNX45', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_glock17`] 			= {['name'] = 'weapon_glock17', 		['label'] = 'Glock 17', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_m4`] 		 		= {['name'] = 'weapon_m4', 	 	['label'] = 'PD M4A1', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_m9`] 			 	= {['name'] = 'weapon_m9', 		['label'] = 'Beretta M9A3', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_m1911`] 			= {['name'] = 'weapon_m1911', 		['label'] = 'M1911', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_uzi`] 			 	= {['name'] = 'weapon_uzi', 		['label'] = 'UZI', 			['ammotype'] = 'AMMO_SMG'},
	[`weapon_mac10`] 			= {['name'] = 'weapon_mac10', 		['label'] = 'MAC-10', 			['ammotype'] = 'AMMO_SMG'},
	[`weapon_mossberg`] 		= {['name'] = 'weapon_mossberg', 	['label'] = 'Mossberg 500', 		['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_remington`] 		= {['name'] = 'weapon_remington', 	['label'] = 'Remington 870', 		['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_scarh`] 		    = {['name'] = 'weapon_scarh', 	['label'] = 'PD SCAR-H', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_shiv`] 		    = {['name'] = 'weapon_shiv', 			['label'] = 'Shiv', 				['ammotype'] = nil},
	[`weapon_katana`] 		    = {['name'] = 'weapon_katana', 			['label'] = 'Katana', 				['ammotype'] = nil},
	[`weapon_sledgehammer`] 	= {['name'] = 'weapon_sledgehammer', 			['label'] = 'Sledge Hammer', 				['ammotype'] = nil},
    [`weapon_ar15`] 		    = {['name'] = 'weapon_ar15', 	 	['label'] = 'PD AR-15', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_mk14`] 		    = {['name'] = 'weapon_mk14', 	 	['label'] = 'PD MK14', 				['ammotype'] = 'AMMO_SNIPER'},	
	[`weapon_huntingrifle`]     = {['name'] = 'weapon_huntingrifle', 	 	['label'] = 'Hunting Rifle', 				['ammotype'] = 'AMMO_SNIPER'},	
	[`weapon_mp9`] 			 	= {['name'] = 'weapon_mp9', 		['label'] = 'MP9', 			['ammotype'] = 'AMMO_SMG'},
	[`weapon_m110`] 		 	= {['name'] = 'weapon_m110', 	 	['label'] = 'M110', 				['ammotype'] = 'AMMO_SNIPER'},	
	[`weapon_hk416`] 		 	= {['name'] = 'weapon_hk416', 	 	['label'] = 'HK-416', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_ak74`] 		 	= {['name'] = 'weapon_ak74', 	 	    ['label'] = 'AK-74', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_aks74`] 		 	= {['name'] = 'weapon_aks74', 	 	    ['label'] = 'AK-S74', 				['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_glock22`] 		 	= {['name'] = 'weapon_glock22', 		['label'] = 'Glock 22', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_glock18c`] 	 	= {['name'] = 'weapon_glock18c', 		['label'] = 'Glock 18C', 			['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_mp5`] 			 	= {['name'] = 'weapon_mp5', 		    ['label'] = 'H&K MP5', 				['ammotype'] = 'AMMO_SMG'},
	[`weapon_colbaton`] 	 	= {['name'] = 'weapon_colbaton', 		['label'] = 'Baton', 				['ammotype'] = nil},	
	[`WEAPON_FN509MRDLE`] 		= {['name'] = 'WEAPON_FN509MRDLE', 		['label'] = 'FN509', 			    ['ammotype'] = 'AMMO_PISTOL'},         
	[`WEAPON_KARAMBIT_FOREST`] 				 = {['name'] = 'WEAPON_KARAMBIT_FOREST', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_SAFARIMESH`] 				 = {['name'] = 'WEAPON_KARAMBIT_SAFARIMESH', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_BOREALFOREST`] 				 = {['name'] = 'WEAPON_KARAMBIT_BOREALFOREST', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_SCORCHED`] 				 = {['name'] = 'WEAPON_KARAMBIT_SCORCHED', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_URBANMASKED`] 				 = {['name'] = 'WEAPON_KARAMBIT_URBANMASKED', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_RUSTCOAT`] 				 = {['name'] = 'WEAPON_KARAMBIT_RUSTCOAT', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_NIGHT`] 				 = {['name'] = 'WEAPON_KARAMBIT_NIGHT', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_STAINED`] 				 = {['name'] = 'WEAPON_KARAMBIT_STAINED', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_ULTRAVIOLET`] 				 = {['name'] = 'WEAPON_KARAMBIT_ULTRAVIOLET', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_BRIGHTWATER`] 				 = {['name'] = 'WEAPON_KARAMBIT_BRIGHTWATER', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_CRIMSONWEB`] 				 = {['name'] = 'WEAPON_KARAMBIT_CRIMSONWEB', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_FREEHAND`] 				 = {['name'] = 'WEAPON_KARAMBIT_FREEHAND', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DAMASCUSSTEEL`] 				 = {['name'] = 'WEAPON_KARAMBIT_DAMASCUSSTEEL', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_CASEHARDENED`] 				 = {['name'] = 'WEAPON_KARAMBIT_CASEHARDENED', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_BLUESTEEL`] 				 = {['name'] = 'WEAPON_KARAMBIT_BLUESTEEL', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_LORE`] 				 = {['name'] = 'WEAPON_KARAMBIT_LORE', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_BLACKLAMINATE`] 				 = {['name'] = 'WEAPON_KARAMBIT_BLACKLAMINATE', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_SLAUGTHER`] 				 = {['name'] = 'WEAPON_KARAMBIT_SLAUGTHER', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_TIGERTOOTH`] 				 = {['name'] = 'WEAPON_KARAMBIT_TIGERTOOTH', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERPHASE1`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERPHASE1', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERPHASE3`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERPHASE3', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_AUTOTRONIC`] 				 = {['name'] = 'WEAPON_KARAMBIT_AUTOTRONIC', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_MARBLEFADE`] 				 = {['name'] = 'WEAPON_KARAMBIT_MARBLEFADE', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERPHASE2`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERPHASE2', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERPHASE4`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERPHASE4', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_GDP1`] 				 = {['name'] = 'WEAPON_KARAMBIT_GDP1', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_GDP3`] 				 = {['name'] = 'WEAPON_KARAMBIT_GDP3', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_GDP4`] 				 = {['name'] = 'WEAPON_KARAMBIT_GDP4', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_FADE`] 				 = {['name'] = 'WEAPON_KARAMBIT_FADE', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_GDP2`] 				 = {['name'] = 'WEAPON_KARAMBIT_GDP2', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_BLACKPEARL`] 				 = {['name'] = 'WEAPON_KARAMBIT_BLACKPEARL', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERRUBY`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERRUBY', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_GDEMERALD`] 				 = {['name'] = 'WEAPON_KARAMBIT_GDEMERALD', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_KARAMBIT_DOPPLERSAPPHIRE`] 				 = {['name'] = 'WEAPON_KARAMBIT_DOPPLERSAPPHIRE', 		['label'] = 'Karambit', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_SCORCHED`] 				 = {['name'] = 'WEAPON_BF_SCORCHED', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_SAFARIMESH`] 				 = {['name'] = 'WEAPON_BF_SAFARIMESH', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_URBANMASKED`] 				 = {['name'] = 'WEAPON_BF_URBANMASKED', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_FOREST`] 				 = {['name'] = 'WEAPON_BF_FOREST', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_BOREALFOREST`] 				 = {['name'] = 'WEAPON_BF_BOREALFOREST', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_ULTRAVIOLET`] 				 = {['name'] = 'WEAPON_BF_ULTRAVIOLET', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_NIGHT`] 				 = {['name'] = 'WEAPON_BF_NIGHT', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_STAINED`] 				 = {['name'] = 'WEAPON_BF_STAINED', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_RUSTCOAT`] 				 = {['name'] = 'WEAPON_BF_RUSTCOAT', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_CASEHARDENED`] 				 = {['name'] = 'WEAPON_BF_CASEHARDENED', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_BLUESTEEL`] 				 = {['name'] = 'WEAPON_BF_BLUESTEEL', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_CRIMSONWEB`] 				 = {['name'] = 'WEAPON_BF_CRIMSONWEB', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DAMASCUSSTEEL`] 				 = {['name'] = 'WEAPON_BF_DAMASCUSSTEEL', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_SLAUGTHER`] 				 = {['name'] = 'WEAPON_BF_SLAUGTHER', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_TIGERTOOTH`] 				 = {['name'] = 'WEAPON_BF_TIGERTOOTH', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERPHASE3`] 				 = {['name'] = 'WEAPON_BF_DOPPLERPHASE3', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERPHASE1`] 				 = {['name'] = 'WEAPON_BF_DOPPLERPHASE1', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERPHASE2`] 				 = {['name'] = 'WEAPON_BF_DOPPLERPHASE2', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_FADE`] 				 = {['name'] = 'WEAPON_BF_FADE', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERPHASE4`] 				 = {['name'] = 'WEAPON_BF_DOPPLERPHASE4', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERBLACKPEARL`] 				 = {['name'] = 'WEAPON_BF_DOPPLERBLACKPEARL', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERRUBY`] 				 = {['name'] = 'WEAPON_BF_DOPPLERRUBY', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_BF_DOPPLERSAPPHIRE`] 				 = {['name'] = 'WEAPON_BF_DOPPLERSAPPHIRE', 		['label'] = 'Butterfly', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_SAFARIMESH`] 				 = {['name'] = 'WEAPON_M9_SAFARIMESH', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_URBANMASKED`] 				 = {['name'] = 'WEAPON_M9_URBANMASKED', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_SCORCHED`] 				 = {['name'] = 'WEAPON_M9_SCORCHED', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_STAINED`] 				 = {['name'] = 'WEAPON_M9_STAINED', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_ULTRAVIOLET`] 				 = {['name'] = 'WEAPON_M9_ULTRAVIOLET', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_BRIGHTWATER`] 				 = {['name'] = 'WEAPON_M9_BRIGHTWATER', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_CRIMSONWEB`] 				 = {['name'] = 'WEAPON_M9_CRIMSONWEB', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_FREEHAND`] 				 = {['name'] = 'WEAPON_M9_FREEHAND', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DAMASCUSSTEEL`] 				 = {['name'] = 'WEAPON_M9_DAMASCUSSTEEL', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_CASEHARDENED`] 				 = {['name'] = 'WEAPON_M9_CASEHARDENED', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_BLUESTEEL`] 				 = {['name'] = 'WEAPON_M9_BLUESTEEL', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_LORE`] 				 = {['name'] = 'WEAPON_M9_LORE', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_BLACKLAMINATE`] 				 = {['name'] = 'WEAPON_M9_BLACKLAMINATE', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_SLAUGTHER`] 				 = {['name'] = 'WEAPON_M9_SLAUGTHER', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_TIGERTOOTH`] 				 = {['name'] = 'WEAPON_M9_TIGERTOOTH', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERP1`] 				 = {['name'] = 'WEAPON_M9_DOPPLERP1', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERP3`] 				 = {['name'] = 'WEAPON_M9_DOPPLERP3', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_AUTOTRONIC`] 				 = {['name'] = 'WEAPON_M9_AUTOTRONIC', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_MARBLEFADE`] 				 = {['name'] = 'WEAPON_M9_MARBLEFADE', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERP2`] 				 = {['name'] = 'WEAPON_M9_DOPPLERP2', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERP4`] 				 = {['name'] = 'WEAPON_M9_DOPPLERP4', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_GDP1`] 				 = {['name'] = 'WEAPON_M9_GDP1', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_GDP3`] 				 = {['name'] = 'WEAPON_M9_GDP3', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_GDP4`] 				 = {['name'] = 'WEAPON_M9_GDP4', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_FADE`] 				 = {['name'] = 'WEAPON_M9_FADE', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_GDP2`] 				 = {['name'] = 'WEAPON_M9_GDP2', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERBLACKPEARL`] 				 = {['name'] = 'WEAPON_M9_DOPPLERBLACKPEARL', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERRUBY`] 				 = {['name'] = 'WEAPON_M9_DOPPLERRUBY', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_GDEMERALD`] 				 = {['name'] = 'WEAPON_M9_GDEMERALD', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	[`WEAPON_M9_DOPPLERSAPPHIRE`] 				 = {['name'] = 'WEAPON_M9_DOPPLERSAPPHIRE', 		['label'] = 'Bayonet', 				['weapontype'] = 'Melee',	['ammotype'] = nil, ['damagereason'] = 'CS GO Knife'},
	-- Melee
	[`weapon_unarmed`] 				 = {['name'] = 'weapon_unarmed', 		['label'] = 'Fists', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_dagger`] 				 = {['name'] = 'weapon_dagger', 		['label'] = 'Dagger', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_bat`] 					 = {['name'] = 'weapon_bat', 			['label'] = 'Bat', 					['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_bottle`] 				 = {['name'] = 'weapon_bottle', 		['label'] = 'Broken Bottle', 		['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_crowbar`] 				 = {['name'] = 'weapon_crowbar', 		['label'] = 'Crowbar', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_flashlight`] 			 = {['name'] = 'weapon_flashlight', 	['label'] = 'Flashlight', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_golfclub`] 			 = {['name'] = 'weapon_golfclub', 		['label'] = 'Golfclub', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_hammer`] 				 = {['name'] = 'weapon_hammer', 		['label'] = 'Hammer', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_hatchet`] 				 = {['name'] = 'weapon_hatchet', 		['label'] = 'Hatchet', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_knuckle`] 				 = {['name'] = 'weapon_knuckle', 		['label'] = 'Knuckle', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_knife`] 				 = {['name'] = 'weapon_knife', 			['label'] = 'Knife', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_machete`] 				 = {['name'] = 'weapon_machete', 		['label'] = 'Machete', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_switchblade`] 			 = {['name'] = 'weapon_switchblade', 	['label'] = 'Switchblade', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_nightstick`] 			 = {['name'] = 'weapon_nightstick', 	['label'] = 'Nightstick', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_wrench`] 				 = {['name'] = 'weapon_wrench', 		['label'] = 'Wrench', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_battleaxe`] 			 = {['name'] = 'weapon_battleaxe', 		['label'] = 'Battle Axe', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_poolcue`] 				 = {['name'] = 'weapon_poolcue', 		['label'] = 'Poolcue', 				['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_briefcase`] 			 = {['name'] = 'weapon_briefcase', 		['label'] = 'Briefcase', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_briefcase_02`] 		 = {['name'] = 'weapon_briefcase_02', 	['label'] = 'Briefcase', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_garbagebag`] 			 = {['name'] = 'weapon_garbagebag', 	['label'] = 'Garbage Bag', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_handcuffs`] 			 = {['name'] = 'weapon_handcuffs', 		['label'] = 'Handcuffs', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_bread`] 				 = {['name'] = 'weapon_bread', 			['label'] = 'Baquette', 			['weapontype'] = 'Melee',	['ammotype'] = nil},
	[`weapon_stone_hatchet`] 		 = {['name'] = 'weapon_stone_hatchet', 	['label'] = 'Stone Hatchet',        ['weapontype'] = 'Melee',	['ammotype'] = nil},

    -- Handguns
	[`weapon_pistol`] 				 = {['name'] = 'weapon_pistol', 		['label'] = 'Pistol', 				    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_pistol_mk2`] 			 = {['name'] = 'weapon_pistol_mk2', 	['label'] = 'Pistol Mk2', 			    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_combatpistol`] 		 = {['name'] = 'weapon_combatpistol', 	['label'] = 'Combat Pistol', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_appistol`] 			 = {['name'] = 'weapon_appistol', 		['label'] = 'AP Pistol', 				['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_stungun`] 				 = {['name'] = 'weapon_stungun', 		['label'] = 'Taser', 					['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_STUNGUN'},
	[`weapon_pistol50`] 			 = {['name'] = 'weapon_pistol50', 		['label'] = 'Pistol .50 Cal', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_snspistol`] 			 = {['name'] = 'weapon_snspistol', 		['label'] = 'SNS Pistol', 				['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_snspistol_mk2`] 	     = {['name'] = 'weapon_snspistol_mk2', 	['label'] = 'SNS Pistol MK2', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_heavypistol`] 			 = {['name'] = 'weapon_heavypistol', 	['label'] = 'Heavy Pistol', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_vintagepistol`] 		 = {['name'] = 'weapon_vintagepistol', 	['label'] = 'Vintage Pistol', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_flaregun`] 			 = {['name'] = 'weapon_flaregun', 		['label'] = 'Flare Gun', 				['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_FLARE'},
	[`weapon_marksmanpistol`] 		 = {['name'] = 'weapon_marksmanpistol', ['label'] = 'Marksman Pistol', 			['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_revolver`] 			 = {['name'] = 'weapon_revolver', 		['label'] = 'Revolver', 				['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_revolver_mk2`] 		 = {['name'] = 'weapon_revolver_mk2', 	['label'] = 'Revolver MK2', 		    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_doubleaction`] 	     = {['name'] = 'weapon_doubleaction', 	['label'] = 'Double Action Revolver',	['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_raypistol`]			 = {['name'] = 'weapon_raypistol',		['label'] = 'Ray Pistol',			    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_ceramicpistol`]		 = {['name'] = 'weapon_ceramicpistol', 	['label'] = 'Ceramic Pistol',		    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_navyrevolver`]        	 = {['name'] = 'weapon_navyrevolver', 	['label'] = 'Navy Revolver',		    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_gadgetpistol`] 		 = {['name'] = 'weapon_gadgetpistol', 	['label'] = 'Gadget Pistol',		    ['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_stungun_mp`] 			 = {['name'] = 'weapon_stungun_mp', 	['label'] = 'Taser', 					['weapontype'] = 'Pistol',	['ammotype'] = 'AMMO_STUNGUN'},

    -- Submachine Guns
	[`weapon_microsmg`] 			 = {['name'] = 'weapon_microsmg', 		['label'] = 'Micro SMG', 			['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_smg`] 				 	 = {['name'] = 'weapon_smg', 			['label'] = 'SMG', 					['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_smg_mk2`] 				 = {['name'] = 'weapon_smg_mk2', 		['label'] = 'SMG MK2', 			    ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_assaultsmg`] 			 = {['name'] = 'weapon_assaultsmg', 	['label'] = 'Assault SMG', 			['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_combatpdw`] 			 = {['name'] = 'weapon_combatpdw', 		['label'] = 'Combat PDW', 			['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_machinepistol`] 		 = {['name'] = 'weapon_machinepistol', 	['label'] = 'Tec-9', 				['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_PISTOL'},
	[`weapon_minismg`] 				 = {['name'] = 'weapon_minismg', 		['label'] = 'Mini SMG', 			['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},
	[`weapon_raycarbine`]	         = {['name'] = 'weapon_raycarbine', 	['label'] = 'Raycarbine',	        ['weapontype'] = 'Submachine Gun',	['ammotype'] = 'AMMO_SMG'},

    -- Shotguns
	[`weapon_pumpshotgun`] 			 = {['name'] = 'weapon_pumpshotgun', 	 	['label'] = 'Pump Shotgun', 			['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_pumpshotgun_mk2`]		 = {['name'] = 'weapon_pumpshotgun_mk2',	['label'] = 'Pump Shotgun MK2', 		['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_sawnoffshotgun`] 		 = {['name'] = 'weapon_sawnoffshotgun', 	['label'] = 'Sawn-off Shotgun', 		['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_assaultshotgun`] 		 = {['name'] = 'weapon_assaultshotgun', 	['label'] = 'Assault Shotgun', 			['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_bullpupshotgun`] 		 = {['name'] = 'weapon_bullpupshotgun', 	['label'] = 'Bullpup Shotgun', 			['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_musket`] 			     = {['name'] = 'weapon_musket', 			['label'] = 'Musket', 					['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_heavyshotgun`] 		 = {['name'] = 'weapon_heavyshotgun', 	 	['label'] = 'Heavy Shotgun', 			['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_dbshotgun`] 			 = {['name'] = 'weapon_dbshotgun', 		 	['label'] = 'Double-barrel Shotgun', 	['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_autoshotgun`] 			 = {['name'] = 'weapon_autoshotgun', 	 	['label'] = 'Auto Shotgun', 			['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},
	[`weapon_combatshotgun`]		 = {['name'] = 'weapon_combatshotgun', 		['label'] = 'Combat Shotgun',		    ['weapontype'] = 'Shotgun',	['ammotype'] = 'AMMO_SHOTGUN'},

    -- Assault Rifles
	[`weapon_assaultrifle`] 		 = {['name'] = 'weapon_assaultrifle', 	 	['label'] = 'Assault Rifle', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_assaultrifle_mk2`] 	 = {['name'] = 'weapon_assaultrifle_mk2', 	['label'] = 'Assault Rifle MK2', 			['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_carbinerifle`] 		 = {['name'] = 'weapon_carbinerifle', 	 	['label'] = 'Carbine Rifle', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
    [`weapon_carbinerifle_mk2`] 	 = {['name'] = 'weapon_carbinerifle_mk2', 	['label'] = 'Carbine Rifle MK2', 			['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_advancedrifle`] 		 = {['name'] = 'weapon_advancedrifle', 	 	['label'] = 'Advanced Rifle', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_specialcarbine`] 		 = {['name'] = 'weapon_specialcarbine', 	['label'] = 'Special Carbine', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_specialcarbine_mk2`]	 = {['name'] = 'weapon_specialcarbine_mk2',	['label'] = 'Specialcarbine MK2',	        ['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_bullpuprifle`] 		 = {['name'] = 'weapon_bullpuprifle', 	 	['label'] = 'Bullpup Rifle', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_bullpuprifle_mk2`]		 = {['name'] = 'weapon_bullpuprifle_mk2', 	['label'] = 'Bull Puprifle MK2',			['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_compactrifle`] 		 = {['name'] = 'weapon_compactrifle', 	 	['label'] = 'Compact Rifle', 				['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
	[`weapon_militaryrifle`]		 = {['name'] = 'weapon_militaryrifle', 		['label'] = 'Military Rifle',   			['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},
    [`weapon_heavyrifle`] 			 = {['name'] = 'weapon_heavyrifle', 	 	['label'] = 'Heavy Rifle', 					['weapontype'] = 'Assault Rifle',	['ammotype'] = 'AMMO_RIFLE'},

    -- Light Machine Guns
	[`weapon_mg`] 					 = {['name'] = 'weapon_mg', 			['label'] = 'Machinegun', 			['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG'},
	[`weapon_combatmg`] 			 = {['name'] = 'weapon_combatmg', 		['label'] = 'Combat MG', 			['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG'},
	[`weapon_combatmg_mk2`]	 		 = {['name'] = 'weapon_combatmg_mk2', 	['label'] = 'Combat MG MK2',	    ['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG'},
	[`weapon_gusenberg`] 			 = {['name'] = 'weapon_gusenberg', 		['label'] = 'Thompson SMG', 		['weapontype'] = 'Light Machine Gun',	['ammotype'] = 'AMMO_MG'},

    -- Sniper Rifles
	[`weapon_sniperrifle`] 			 = {['name'] = 'weapon_sniperrifle', 	 	['label'] = 'Sniper Rifle', 			['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER'},			
	[`weapon_heavysniper`] 			 = {['name'] = 'weapon_heavysniper', 	 	['label'] = 'Heavy Sniper', 			['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER'},			
	[`weapon_heavysniper_mk2`]		 = {['name'] = 'weapon_heavysniper_mk2', 	['label'] = 'Heavysniper MK2',	        ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER'},			
	[`weapon_marksmanrifle`] 		 = {['name'] = 'weapon_marksmanrifle', 	 	['label'] = 'Marksman Rifle', 			['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER'},			
	[`weapon_marksmanrifle_mk2`]	 = {['name'] = 'weapon_marksmanrifle_mk2',	['label'] = 'Marksman Rifle MK2',	    ['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER'},			
	[`weapon_remotesniper`] 		 = {['name'] = 'weapon_remotesniper', 	 	['label'] = 'Remote Sniper', 			['weapontype'] = 'Sniper Rifle',	['ammotype'] = 'AMMO_SNIPER_REMOTE'},	

    -- Heavy Weapons
	[`weapon_rpg`] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 						['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_RPG'},				
	[`weapon_grenadelauncher`] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Grenade Launcher', 		['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_GRENADELAUNCHER'},	
	[`weapon_grenadelauncher_smoke`] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Smoke Grenade Launcher',	['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_GRENADELAUNCHER'},	
	[`weapon_minigun`] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Minigun', 					['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_MINIGUN'},			
	[`weapon_firework`] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Firework Launcher', 		['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil},						
	[`weapon_railgun`] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Railgun', 					['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil},						
	[`weapon_hominglauncher`] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Homing Launcher', 			['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_STINGER'},			
	[`weapon_compactlauncher`] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Compact Launcher', 		['weapontype'] = 'Heavy Weapons',	['ammotype'] = nil},						
	[`weapon_rayminigun`]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Ray Minigun',		        ['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_MINIGUN'},			
    [`weapon_emplauncher`] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'EMP Launcher', 			['weapontype'] = 'Heavy Weapons',	['ammotype'] = 'AMMO_EMPLAUNCHER'},

    -- Throwables
	[`weapon_grenade`] 		        = {['name'] = 'weapon_grenade', 		['label'] = 'Grenade', 			['weapontype'] = 'Throwable',	['ammotype'] = nil},			
	[`weapon_bzgas`] 		        = {['name'] = 'weapon_bzgas', 			['label'] = 'BZ Gas', 			['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_molotov`] 		        = {['name'] = 'weapon_molotov', 		['label'] = 'Molotov', 			['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_stickybomb`] 	        = {['name'] = 'weapon_stickybomb', 	    ['label'] = 'C4', 				['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_proxmine`] 	        = {['name'] = 'weapon_proxmine', 		['label'] = 'Proxmine Grenade', ['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_snowball`] 	        = {['name'] = 'weapon_snowball', 		['label'] = 'Snowball', 		['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_pipebomb`] 	        = {['name'] = 'weapon_pipebomb', 		['label'] = 'Pipe Bomb', 		['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_ball`] 		        = {['name'] = 'weapon_ball', 			['label'] = 'Ball', 			['weapontype'] = 'Throwable',	['ammotype'] = 'AMMO_BALL'},	
	[`weapon_smokegrenade`]         = {['name'] = 'weapon_smokegrenade', 	['label'] = 'Smoke Grenade', 	['weapontype'] = 'Throwable',	['ammotype'] = nil},
	[`weapon_flare`] 		        = {['name'] = 'weapon_flare', 			['label'] = 'Flare pistol', 	['weapontype'] = 'Throwable',	['ammotype'] = 'AMMO_FLARE'},
	[`weapon_flashbang`]         	= {['name'] = 'weapon_flashbang', 	['label'] = 'Flashbang', 	['weapontype'] = 'Throwable',	['ammotype'] = nil},

    -- Miscellaneous
	[`weapon_petrolcan`] 			= {['name'] = 'weapon_petrolcan', 		 	['label'] = 'Petrol Can', 				['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_PETROLCAN'},
	[`gadget_parachute`] 			= {['name'] = 'gadget_parachute', 		 	['label'] = 'Parachute', 				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_fireextinguisher`] 	= {['name'] = 'weapon_fireextinguisher',	['label'] = 'Fire Extinguisher',		['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_hazardcan`]			= {['name'] = 'weapon_hazardcan',			['label'] = 'Hazardcan',			    ['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_PETROLCAN'},
    [`weapon_fertilizercan`]		= {['name'] = 'weapon_fertilizercan',		['label'] = 'Fertilizer Can',			['weapontype'] = 'Miscellaneous',	['ammotype'] = 'AMMO_FERTILIZERCAN'},
	[`weapon_barbed_wire`]			= {['name'] = 'weapon_barbed_wire',			['label'] = 'Barbed Wire',				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_drowning`]				= {['name'] = 'weapon_drowning',			['label'] = 'Drowning',					['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_drowning_in_vehicle`]	= {['name'] = 'weapon_drowning_in_vehicle',	['label'] = 'Drowning in a Vehicle',	['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_bleeding`]				= {['name'] = 'weapon_bleeding',			['label'] = 'Bleeding',					['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_electric_fence`]		= {['name'] = 'weapon_electric_fence',		['label'] = 'Electric Fence',			['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_explosion`]			= {['name'] = 'weapon_explosion',			['label'] = 'Explosion',				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_fall`]					= {['name'] = 'weapon_fall',				['label'] = 'Fall',						['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_exhaustion`]			= {['name'] = 'weapon_exhaustion',			['label'] = 'Exhaustion',				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_hit_by_water_cannon`]	= {['name'] = 'weapon_hit_by_water_cannon',	['label'] = 'Water Cannon',				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_rammed_by_car`]		= {['name'] = 'weapon_rammed_by_car',		['label'] = 'Rammed - Vehicle',			['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_run_over_by_car`]		= {['name'] = 'weapon_run_over_by_car',		['label'] = 'Run Over - Vehicle',		['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_heli_crash`]			= {['name'] = 'weapon_heli_crash',			['label'] = 'Heli Crash',				['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},
	[`weapon_fire`]					= {['name'] = 'weapon_fire',				['label'] = 'Fire',						['weapontype'] = 'Miscellaneous',	['ammotype'] = nil},

	-- Animals
    [`weapon_animal`]               = {['name'] = 'weapon_animal',	['label'] = 'Animal',	['weapontype'] = 'Animals',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},
    [`weapon_cougar`]               = {['name'] = 'weapon_cougar',	['label'] = 'Cougar',	['weapontype'] = 'Animals',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},

	-- Chop Shop 
	weapon_digiscanner = {name = 'weapon_digiscanner', label = 'Digital Scanner', weight = 100, type = 'weapon', ammotype = nil, image = "WEAPON_DIGISCANNER.png", unique = true, useable = false, description = 'Signal scanner'},


}
